name: Repository Dispatch
on:
  repository_dispatch:
    types: [my-event]
jobs:
  myEvent:
    runs-on: ubuntu-latest
    steps:
      - name: Dump the client payload context
        env:
          PAYLOAD_CONTEXT: ${{ toJson(github.event.client_payload) }}
        run: echo "$PAYLOAD_CONTEXT"

      - uses: actions/checkout@v2
        if: github.event.client_payload.ref != ''
        with:
          ref: ${{ github.event.client_payload.ref }}

      - run: echo ${{ github.event.client_payload.sha }}

      - name: Make changes to pull request
        run: |
          touch 123

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.MONO_TOKEN }}
          commit-message: Update report
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: update-submodules
          delete-branch: true
          title: '[Dispatch] Update submodules'
          body: |
            Update report
            - Updated with *today's* date
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            report
            automated pr
          assignees: n0str
          reviewers: n0str
          team-reviewers: |
            owners
            maintainers
          draft: false