name: Update submodules
on:
  repository_dispatch:
    types: [submodule-changed]
jobs:
  submoduleChanged:
    runs-on: ubuntu-latest
    steps:
      - name: Show payload content
        env:
          PAYLOAD_CONTEXT: ${{ toJson(github.event.client_payload) }}
        run: echo "$PAYLOAD_CONTEXT"

      - uses: actions/checkout@v2
        if: github.event.client_payload.ref != ''
        with:
          ref: ${{ github.event.client_payload.ref }}

      - name: Update submodules to the master branch
        run: |
          git submodule sync
          git submodule update --init --recursive
          git submodule update --recursive --remote

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Add changes of ${{ PAYLOAD_CONTEXT.path }}" -a

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.MONO_TOKEN }}
